kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    imageregistry.openshift.io: 'true'
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: nfs-storage-provisioner
  selfLink: >-
    /api/v1/namespaces/openshift-image-registry/persistentvolumeclaims/image-registry-storage
  resourceVersion: '18629'
  name: image-registry-storage
  uid: 26cc804a-4ec2-4f52-b6e5-84404b4b9def
  creationTimestamp: '2020-08-05T18:36:16Z'
  managedFields:
    - manager: cluster-image-registry-operator
      operation: Update
      apiVersion: v1
      time: '2020-08-05T18:36:16Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:imageregistry.openshift.io': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:volumeMode': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2020-08-05T18:36:19Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
        'f:spec':
          'f:volumeName': {}
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
  namespace: openshift-image-registry
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pvc-26cc804a-4ec2-4f52-b6e5-84404b4b9def
  storageClassName: nfs-storage
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
