apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"zero-autoscaler:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"zero-autoscaler\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2020-10-23T09:06:54Z"
  generation: 5
  labels:
    app: zero-autoscaler
    app.kubernetes.io/component: zero-autoscaler
    app.kubernetes.io/instance: zero-autoscaler
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:image.openshift.io/triggers: {}
          f:openshift.io/generated-by: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/instance: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:deployment: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:openshift.io/generated-by: {}
            f:labels:
              .: {}
              f:deployment: {}
          f:spec:
            f:containers:
              k:{"name":"zero-autoscaler"}:
                .: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: oc
    operation: Update
    time: "2020-10-23T09:06:54Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"zero-autoscaler"}:
                f:image: {}
    manager: openshift-controller-manager
    operation: Update
    time: "2020-10-23T09:09:12Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:replicas: {}
        f:template:
          f:spec:
            f:containers:
              k:{"name":"zero-autoscaler"}:
                f:args: {}
                f:ports:
                  .: {}
                  k:{"containerPort":80,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
    manager: Mozilla
    operation: Update
    time: "2020-10-23T09:58:51Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"ReplicaFailure"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:unavailableReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-10-23T09:58:51Z"
  name: zero-autoscaler
  namespace: comprehensive-review
  resourceVersion: "161549"
  selfLink: /apis/apps/v1/namespaces/comprehensive-review/deployments/zero-autoscaler
  uid: 3c36fe77-1ec6-45d5-b8e1-17dd5a668352
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: zero-autoscaler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: zero-autoscaler
    spec:
      containers:
      - args:
        - --namespace=$(comprehensive-review)
        - --address=0.0.0.0:80
        - --deployment=hello-world-nginx
        - --endpoints=hello-world-nginx
        - --target=hello-world-nginx:8080
        image: image-registry.openshift-image-registry.svc:5000/comprehensive-review/zero-autoscaler@sha256:dc50f5b04200bfdd4a3f31af013e6a514ceebf8901201bd5b3595dad658f5d92
        imagePullPolicy: IfNotPresent
        name: zero-autoscaler
        ports:
        - containerPort: 80
          name: proxy
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: zero-autoscaler
      serviceAccountName: zero-autoscaler
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-10-23T09:06:54Z"
    lastUpdateTime: "2020-10-23T09:54:31Z"
    message: ReplicaSet "zero-autoscaler-7fdb58cd96" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-10-23T09:58:51Z"
    lastUpdateTime: "2020-10-23T09:58:51Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-10-23T09:58:51Z"
    lastUpdateTime: "2020-10-23T09:58:51Z"
    message: 'pods "zero-autoscaler-7fdb58cd96-" is forbidden: error looking up service
      account comprehensive-review/zero-autoscaler: serviceaccount "zero-autoscaler"
      not found'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 5
  unavailableReplicas: 1
